name: Deploy

on:
  workflow_dispatch: {}
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git checkout "${GITHUB_REF:10}"

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - run: yarn install
        env:
          CI: true

      - name: test
        run: yarn test
        env:
          CI: true

      - name: publish
        run: lerna exec -- npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
