name: Unit Tests (PR)

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: yarn install
        env:
          CI: true

      - name: test
        run: yarn test
        env:
          CI: true
